//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barbershop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry
    {
        public int ID { get; set; }
        public Nullable<int> Client { get; set; }
        public Nullable<int> Employee { get; set; }
        public Nullable<int> Service { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Administrator { get; set; }
    
        public virtual Administrator Administrator1 { get; set; }
        public virtual Client Client1 { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Service Service1 { get; set; }
    }
}
